on: push
jobs:
  Tests-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: make install
      - run: make test
      - run: make lint